### ISSUE TITLE
Uhrzeit beim Import von Trakt 

### ISSUE THREAD

**Issue by carstenheine** [serienguide/serienguide#1]
Die Uhrzeit zwischen Trakt und Serienguide differiert um genau eine Stunde. 
Episode die bei Trakt um 22:15 Uhr gesehen wurden, ist nach dem Import bei Serienguide um 21:15 Uhr gesehen.

**Comment by danielsundermeier** [comment]
Ab jetzt werden die richtigen Zeiten importiert. Alles, was davor importiert wurde hat noch die flasche Zeit
