### ISSUE TITLE
Seitennavigation 

### ISSUE THREAD

**Issue by carstenheine** [serienguide/serienguide#11]
Auf den Seiten "Gesehen" und "Bewertet" kann man nicht mit der Seitennavigation auf eine andere Seite wechseln.

**Comment by danielsundermeier** [comment]
Es scheint auch mit dem Package zu tun zu haben.
Ich weiß noch nicht, wie ich das löse.

Ich nutze es für die fast alle Seiten und würde es ungerne austauschen
