### ISSUE TITLE
Wechsel von "Gesehen" auf "Erstellt"

### ISSUE THREAD

**Issue by carstenheine** [serienguide/serienguide#12]
Der Wechsel zwischen "Gesehen" und "Erstellt" scheint nicht immer zu funktionieren, zumindest von Erstellt zurück zu gesehen.
Es ist auch nicht ersichtlich, in welcher Ansicht man sich gerade befindet.

**Comment by danielsundermeier** [comment]
Es liegt am Package Livewire.
Ich weiß nicht, wie ich das beheben kann.

**Comment by danielsundermeier** [comment]
Ich habe jetzt die Meisten Ansichten umgestellt.

Bitte testen.

**Comment by carstenheine** [comment]
Es sieht so aus, als wenn es jetzt funktionierte.
