### ISSUE TITLE
Server 500 Error

### ISSUE THREAD

**Issue by ASSOLI** [serienguide/serienguide#13]
Beim importieren von dem Film "Magic Beyond Words" bekomme ich einen 500 Server Error und nichts wir importiert.

**Comment by danielsundermeier** [comment]
Es liegt am Package Livewire.
Ich weiß nicht, wie ich das beheben kann.

**Comment by ASSOLI** [comment]
Aha, das ist natürlich schlecht wenn der Fehler in einem externen Modul liegt. Es kommt der Fehler ja auch nur bei diesem Film, sonst funktioniert das alles sehr gut. 

Gibt es eigentlich eine Möglichkeit Filme ( oder Serien) auch manuell hinzuzufügen?

**Comment by danielsundermeier** [comment]
Ich habe den Film über die Datenbank importiert.
https://www.serienguide.tv/movies/magic-beyond-words-die-zauberhafte-geschichte-der-jk-rowling-2011

Ich überlege mir etwas zum Importieren. 
Vielleicht indem man die ID von https://www.themoviedb.org/movie/80530-magic-beyond-words-the-jk-rowling-story eingibt.

**Comment by ASSOLI** [comment]
Cool. 

Vielleicht liegt der Fehler ja auch an irgendwelchen Sonderzeichen in einem der Texten!

**Comment by danielsundermeier** [comment]
Ich habe den Import komplett umgebaut. Bitte einmal testen
