### ISSUE TITLE
Wieder einmal Trakt.tv

### ISSUE THREAD

**Issue by carstenheine** [serienguide/serienguide#14]
Seit zwei Tagen funktioniert der automatische Sync mit trakt.tv leider nicht mehr.
Die manuelle Synchronisation endet in einem Error 500.

Gruß,
Carsten

**Comment by danielsundermeier** [comment]
Kannst Du die Verbindung löschen, neu verbinden und dann nochmal testen?

**Comment by carstenheine** [comment]
Lässt sich dann nicht mehr anlegen. Das führt zu einem oauth-Fehler: The requested redirect uri is malformed or doesn't match client redirect URI.
![F33AF9E9-CB98-4420-BB56-51172835A355](https://user-images.githubusercontent.com/76074834/111897587-0a856400-8a21-11eb-850b-2f3a6d0834b4.png)

**Comment by carstenheine** [comment]
Geht wieder ... 
Lag vermutlich an Trakt selber. Ich habe jetzt erst gemerkt, dass Emby auch Probleme hatte.
