### ISSUE TITLE
Fehlerhafte Serie lässt sich nicht aktualisieren.

### ISSUE THREAD

**Issue by ASSOLI** [serienguide/serienguide#17]
Die Serie 'Outer Banks' ist bereits in den Serien vorhanden, doch gibt es dort keine Informationen zur Serie.
Kein Bild. Keine Staffeln.
Die Serie hat bereits 3 Staffeln.

Ein mehrfaches Aktualisieren der Serie hat auch nicht geholfen.

**Comment by danielsundermeier** [comment]
Die Daten sind jetzt wieder da.
Es gab noch eine zweite Serie mit dem selben Link, die habe ich gelöscht.

https://www.serienguide.tv/shows/outer-banks-2020
