### ISSUE TITLE
500 Internal Server Error bei Links zu Filmen 

### ISSUE THREAD

**Issue by ASSOLI** [serienguide/serienguide#4]
Alle Links zu Filmen führen zu einem
 
500 Internal Server Error

Hier sind einige davon
https://www.serienguide.tv/movies/the-gentlemen
https://www.serienguide.tv/movies/the-midnight-sky
https://www.serienguide.tv/movies/ready-or-not

**Comment by danielsundermeier** [comment]
Geht jetzt wieder.
Danke für den Hinweis
