### ISSUE TITLE
Smartphone nicht alle Punkte verfügbar

### ISSUE THREAD

**Issue by carstenheine** [serienguide/serienguide#5]
Im Menü auf einem mobilen Endgerät ist der Menüpunkte Listen und Verbindung nicht verfügbar.

**Comment by ASSOLI** [comment]
Als Tipp nimm dein Handy mal im Querformat in die Hand, nun müsstest du etwas mehr Möglichkeiten habe.

**Comment by carstenheine** [comment]
Stimmt, im Querformat geht's. Danke.

**Comment by danielsundermeier** [comment]
Ich habe die beiden Punkte im mobilen Menu hinzugefügt.
Danke für den Hinweis
