### ISSUE TITLE
500 Internal Server Error auschecken beim Import von Filmen

### ISSUE THREAD

**Issue by ASSOLI** [serienguide/serienguide#6]
Auch beim importieren von neuen Filmen kommt es zu einem 500 Internal Server Error.

**Comment by danielsundermeier** [comment]
Bitte einmal testen.
Bei welchem Film hat es nicht funktioniert?

**Comment by ASSOLI** [comment]
Habe es mit dem Film "Das perfekte Weihnachten" aus probiert und es gab diesmal keinen Fehler. Doch wurde bei dem Film kein Bild übernommen.
