### ISSUE TITLE
Suche nach „Kill „ führt zu 500 Internal Server Error

### ISSUE THREAD

**Issue by ASSOLI** [serienguide/serienguide#8]
Gibt man auf der Dashboard Seite im Suchfeld "Kill " ein um nach dem Film "Kill Chain" zu suchen wird ein 
'500 Internal Server Error'
ausgelöst. 
![image](https://user-images.githubusercontent.com/15950373/103937810-975e9800-5129-11eb-9454-197702f7ed54.png)

**Comment by danielsundermeier** [comment]
ist es behoben?
